### ISSUE TITLE
sin and cos are not working

### ISSUE THREAD

**Issue by shujidev** [treeform/shady#3]
Any example trying to compile a proc with `sin` or `cos` into `toGLSL` throws the next error:

```
nim c -f  --run --hints:off --threads:off "test.nim"
stack trace: (most recent call last)
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(784, 21) toGLSL
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(747, 17) toGLSLInner
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(731, 19) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(729, 38) gatherFunction
C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(623, 11) procDef
C:\nim-1.6.0\lib\system\assertions.nim(38, 26) failedAssertImpl
C:\nim-1.6.0\lib\system\assertions.nim(28, 11) raiseAssert
C:\nim-1.6.0\lib\system\fatal.nim(53, 5) sysFatal
C:\Users\cravs\Desktop\test.nim(57, 20) template/generic instantiation of `toGLSL` from here
C:\nim-1.6.0\lib\system\fatal.nim(53, 5) Error: unhandled exception: C:\Users\cravs\.nimble\pkgs\shady-0.0.1\shady.nim(623, 10) `topLevelNode.kind == nnkProcDef`  [AssertionDefect]
```

The code is working fine with this code:
var testColor: Vec4
circleSmooth(testColor, vec2(100, 100), 0.0)

By the way, it is not clear to me how to get an array with an Image data so I can load it into something like Pixie, from what I undestand there is only a function to get every pixel coordinate, am I right?

**Comment by treeform** [comment]
Do you have super simplified example of the code that is failing to compile?

**Comment by treeform** [comment]
example/colors both use sin and cos and it appears to work fine.

**Comment by treeform** [comment]
I don't understand your second question. Shady generates shaders. If you want to get that data back into an image, you might what to look at compute shaders? There is a lot of other openGL machinery needed to make it all work.

**Comment by treeform** [comment]
I am going to close this issue. I am not sure what is wrong? Feel free to reopen if you have a repro case. It appears everything is working and I heard no response.
