### ISSUE TITLE
Missing opengl dependency

### ISSUE THREAD

**Issue by arkanoid87** [treeform/shady#9]
just installed shady in a clean environment, got this error with `nimble build`

```nim
shady-0.1.3/shady/demo.nim(3, 8) Error: cannot open file: opengl
```

please mind that I've not been running nimble build in shady install directory, but in a new clean project with just src/my_test_shady_proj.nim

**Comment by treeform** [comment]
Yes, shady is just nim code to GLSL macro, in theory it needs nothing but Nim and vmath.

But the examples would be pretty boring if they just printed text output.
